- id:  doi:10.1111/cogs.12823
  type: paper
  description: Our goal is to develop a minimal cognitive model of HSR that can learn to map over-time speech to semantics, without explicit phonetic training as a first step in bridging the gap between HSR and ASR.
  date: 2020-02-05
  image: images/earshot.png
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/comp-cogneuro-lang/EARShot_TF2
  tags:
    - open science
    - collaboration

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
